### PR TITLE
Updates dependencies

### PR DESCRIPTION
**Pull request by tomcardoso**
Addresses https://github.com/lukechilds/react-jsdom/issues/7.

### CODE REVIEW

**Comment by lukechilds** [comment]
Thanks for this. Are you able to just updated React in this PR? I'll update the other dependencies separately.

**Comment by chrisalcantara** [comment]
@lukechilds Any updates on merging this? I ran into the same issue as Tom.

**Comment by lukechilds** [comment]
@chrisalcantara Yeah, sorry I've been super busy on paid work and haven't had much time for OSS.

If you're able to clean up the PR with the above notes I'll publish a new release.

**Comment by lukechilds** [comment]
Sorry for the delay on this!

**Pull request merged**
